/**
 * generateExecutionPack — maps card output fields to a zip-ready file map.
 * Returns Record<path, utf-8 string content>
 */

export interface CardData {
  shareId: string;
  title: string | null;
  classification: string;
  output: unknown;
  createdAt: Date;
}

// ── Simple YAML serialiser (handles 1-level nesting) ─────────────────────────
function toYaml(obj: Record<string, unknown>, indent = 0): string {
  const pad = '  '.repeat(indent);
  return Object.entries(obj)
    .map(([k, v]) => {
      if (v == null) return `${pad}${k}: ~`;
      if (typeof v === 'object' && !Array.isArray(v)) {
        return `${pad}${k}:\n${toYaml(v as Record<string, unknown>, indent + 1)}`;
      }
      if (Array.isArray(v)) {
        const items = (v as unknown[]).map(i => `${pad}  - ${String(i)}`).join('\n');
        return `${pad}${k}:\n${items}`;
      }
      // Quote strings that need it
      const s = String(v);
      const needsQuote = s.includes(':') || s.includes('#') || s.includes('\n') || s.includes('"');
      return `${pad}${k}: ${needsQuote ? `"${s.replace(/"/g, '\\"')}"` : s}`;
    })
    .join('\n');
}

// ── Checklist builder ─────────────────────────────────────────────────────────
function checklist(items: string[], header = ''): string {
  const lines = items.map(item => `- [ ] ${item}`).join('\n');
  return header ? `${header}\n\n${lines}` : lines;
}

// ── Python test scaffold ──────────────────────────────────────────────────────
function pythonTestScaffold(title: string, steps: string[]): string {
  const testFns = steps.slice(0, 3).map((step, i) => {
    const name = step.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '_').toLowerCase().slice(0, 40) || `step_${i + 1}`;
    return `def test_${name}():\n    # TODO: implement test for: ${step}\n    pass`;
  });

  return `"""
Starter tests for: ${title}
Generated by Vext — https://vext.so
"""

import pytest


${testFns.join('\n\n')}


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
`;
}

// ── Per-classification file generators ───────────────────────────────────────

type FileMap = Record<string, string>;

function packSetupTutorial(data: CardData): FileMap {
  const o = data.output as any;
  const title = data.title ?? 'Setup Tutorial';
  const steps: string[] = o.steps ?? [];
  const snippets: Record<string, string> = o.configSnippets ?? {};
  const files: string[] = o.generatedFiles ?? [];

  const systemPrompt = `# System Prompt — ${title}

You are an expert assistant helping implement the following setup/tutorial exactly as described.

## Your Role
Guide the user through each step precisely. If they get stuck, refer to the numbered steps below.
Do not skip steps. Confirm completion before moving to the next.

## Steps to Follow
${steps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

${files.length ? `## Files to Create/Modify\n${files.map(f => `- \`${f}\``).join('\n')}` : ''}

## Rules
- Follow steps in order.
- Use exact config values provided.
- Ask clarifying questions only if a step is ambiguous.
- Confirm each step is complete before proceeding.
`.trimEnd();

  const configYaml = `# Vext Config — ${title}
# Generated: ${new Date().toISOString()}

metadata:
  title: "${title}"
  classification: setup/tutorial
  share_id: "${data.shareId}"

${Object.keys(snippets).length > 0 ? `config_snippets:\n${Object.entries(snippets).map(([k, v]) => `  ${k}: |\n    ${v.replace(/\n/g, '\n    ')}`).join('\n')}` : '# No config snippets extracted'}

generated_files:
${files.length ? files.map(f => `  - "${f}"`).join('\n') : '  []'}
`;

  const md = `# Setup Checklist — ${title}

> Generated by [Vext](https://vext.so/card/${data.shareId}) on ${new Date().toLocaleDateString()}

## Steps

${checklist(steps)}

${files.length ? `## Files to Create\n\n${files.map(f => `- [ ] \`${f}\``).join('\n')}` : ''}
`.trimEnd();

  const files_map: FileMap = {
    'prompts/system-prompt.md': systemPrompt,
    'configs/config.yaml': configYaml,
    'scripts/setup-checklist.md': md,
  };

  if (Object.keys(snippets).length > 0) {
    files_map['tests/starter-test.py'] = pythonTestScaffold(title, steps);
  }

  return files_map;
}

function packStrategyFramework(data: CardData): FileMap {
  const o = data.output as any;
  const title = data.title ?? 'Strategy Framework';
  const methodology: string = o.methodology ?? '';
  const principles: string[] = o.keyPrinciples ?? [];
  const frameworks: string[] = o.frameworks ?? [];
  const decisionTree: string = o.decisionTree ?? '';

  const systemPrompt = `# System Prompt — ${title}

You are a strategic advisor helping implement the following framework.

## Methodology
${methodology}

## Key Principles
${principles.map((p, i) => `${i + 1}. ${p}`).join('\n')}

${decisionTree ? `## Decision Tree\n${decisionTree}` : ''}

${frameworks.length ? `## Referenced Frameworks\n${frameworks.map(f => `- ${f}`).join('\n')}` : ''}

## Instructions
When advising, always ground recommendations in the principles above.
Present trade-offs clearly and map decisions to the framework.
`.trimEnd();

  const configYaml = `# Vext Config — ${title}
# Generated: ${new Date().toISOString()}

metadata:
  title: "${title}"
  classification: strategy/framework
  share_id: "${data.shareId}"

methodology: "${methodology.replace(/"/g, '\\"')}"

key_principles:
${principles.map(p => `  - "${p.replace(/"/g, '\\"')}"`).join('\n') || '  []'}

related_frameworks:
${frameworks.map(f => `  - "${f}"`).join('\n') || '  []'}
`;

  const md = `# Strategy Checklist — ${title}

> Generated by [Vext](https://vext.so/card/${data.shareId})

## Methodology
${methodology}

## Implementation Checklist

${checklist(principles)}

${frameworks.length ? `## Frameworks to Study\n\n${frameworks.map(f => `- [ ] ${f}`).join('\n')}` : ''}
`.trimEnd();

  return {
    'prompts/system-prompt.md': systemPrompt,
    'configs/config.yaml': configYaml,
    'scripts/setup-checklist.md': md,
  };
}

function packToolDemo(data: CardData): FileMap {
  const o = data.output as any;
  const title = data.title ?? 'Tool Demo';
  const toolName: string = o.toolName ?? 'Tool';
  const features: string[] = o.features ?? [];
  const useCases: string[] = o.useCases ?? [];
  const pros: string[] = o.prosCons?.pros ?? [];
  const cons: string[] = o.prosCons?.cons ?? [];

  const systemPrompt = `# System Prompt — ${title}

You are an expert on ${toolName}. Help the user understand and use it effectively.

## Tool: ${toolName}

## Key Features
${features.map(f => `- ${f}`).join('\n')}

## Primary Use Cases
${useCases.map((u, i) => `${i + 1}. ${u}`).join('\n')}

## Strengths & Limitations
**Strengths:** ${pros.join(', ')}
**Limitations:** ${cons.join(', ')}

## Instructions
Provide concrete examples for each feature. Always acknowledge limitations honestly.
Recommend ${toolName} only when it genuinely fits the use case.
`.trimEnd();

  const configYaml = `# Vext Config — ${toolName} Demo
# Generated: ${new Date().toISOString()}

metadata:
  title: "${title}"
  classification: tool/demo
  tool_name: "${toolName}"
  share_id: "${data.shareId}"

evaluation:
  pros:
${pros.map(p => `    - "${p.replace(/"/g, '\\"')}"`).join('\n') || '    []'}
  cons:
${cons.map(c => `    - "${c.replace(/"/g, '\\"')}"`).join('\n') || '    []'}

use_cases:
${useCases.map(u => `  - "${u.replace(/"/g, '\\"')}"`).join('\n') || '  []'}
`;

  const md = `# ${toolName} Evaluation Checklist

> Generated by [Vext](https://vext.so/card/${data.shareId})

## Features to Test

${checklist(features)}

## Use Cases to Validate

${checklist(useCases)}

## Pros vs Cons

| Pros | Cons |
|------|------|
${Math.max(pros.length, cons.length) > 0
    ? Array.from({ length: Math.max(pros.length, cons.length) })
        .map((_, i) => `| ${pros[i] ?? ''} | ${cons[i] ?? ''} |`)
        .join('\n')
    : '| — | — |'}
`.trimEnd();

  return {
    'prompts/system-prompt.md': systemPrompt,
    'configs/config.yaml': configYaml,
    'scripts/setup-checklist.md': md,
    'tests/starter-test.py': pythonTestScaffold(toolName, features),
  };
}

function packFinanceSetup(data: CardData): FileMap {
  const o = data.output as any;
  const title = data.title ?? 'Finance Setup';
  const strategy: string = o.strategy ?? '';
  const riskParams: Record<string, string> = o.riskParameters ?? {};
  const backtest = o.backtestResults ?? {};
  const snippets: Record<string, string> = o.configSnippets ?? {};

  const systemPrompt = `# System Prompt — ${title}

You are a quantitative trading assistant implementing the following strategy.

## Strategy
${strategy}

## Risk Parameters
${Object.entries(riskParams).map(([k, v]) => `- **${k}**: ${v}`).join('\n')}

${backtest && Object.keys(backtest).length
    ? `## Backtest Performance\n${[
        backtest.sharpeRatio != null ? `- Sharpe Ratio: ${backtest.sharpeRatio}` : '',
        backtest.maxDrawdown != null ? `- Max Drawdown: ${backtest.maxDrawdown}%` : '',
        backtest.winRate != null ? `- Win Rate: ${backtest.winRate}%` : '',
      ].filter(Boolean).join('\n')}`
    : ''}

## Instructions
Implement trades ONLY within the defined risk parameters.
Always confirm current market conditions before execution.
Never override the risk limits. Log all decisions with rationale.

## ⚠️ Disclaimer
This is educational content only — not financial advice.
`.trimEnd();

  const configYaml = `# Vext Finance Config — ${title}
# Generated: ${new Date().toISOString()}
# ⚠️ DISCLAIMER: Educational only. Not financial advice.

metadata:
  title: "${title}"
  classification: finance/setup
  share_id: "${data.shareId}"

strategy:
  description: "${strategy.replace(/"/g, '\\"').slice(0, 200)}"

risk_parameters:
${Object.entries(riskParams).map(([k, v]) => `  ${k}: "${v}"`).join('\n') || '  {}'}

backtest_results:
${backtest.sharpeRatio != null ? `  sharpe_ratio: ${backtest.sharpeRatio}` : '  sharpe_ratio: ~'}
${backtest.maxDrawdown != null ? `  max_drawdown_pct: ${backtest.maxDrawdown}` : '  max_drawdown_pct: ~'}
${backtest.winRate != null ? `  win_rate_pct: ${backtest.winRate}` : '  win_rate_pct: ~'}

${Object.keys(snippets).length ? `config_snippets:\n${Object.entries(snippets).map(([k, v]) => `  ${k}: |\n    ${v.replace(/\n/g, '\n    ')}`).join('\n')}` : ''}
`;

  const md = `# Finance Setup Checklist — ${title}

> Generated by [Vext](https://vext.so/card/${data.shareId})
> ⚠️ Educational purposes only — not financial advice.

## Strategy Overview
${strategy}

## Pre-Trade Checklist

- [ ] Verify all risk parameters are configured
- [ ] Confirm backtesting is complete
- [ ] Paper trade for minimum 2 weeks
- [ ] Set stop-loss levels per risk params
- [ ] Define position sizing rules
- [ ] Configure alerts and monitoring

## Risk Parameters

${Object.entries(riskParams).map(([k, v]) => `- [ ] **${k}**: ${v}`).join('\n') || '- [ ] Define risk parameters'}
`.trimEnd();

  return {
    'prompts/system-prompt.md': systemPrompt,
    'configs/config.yaml': configYaml,
    'scripts/setup-checklist.md': md,
    'tests/starter-test.py': pythonTestScaffold(title, Object.keys(riskParams).map(k => `Validate ${k} = ${riskParams[k]}`)),
  };
}

function packProductTeardown(data: CardData): FileMap {
  const o = data.output as any;
  const title = data.title ?? 'Product Teardown';
  const productName: string = o.productName ?? 'Product';
  const strengths: string[] = o.strengths ?? [];
  const weaknesses: string[] = o.weaknesses ?? [];
  const targetAudience: string = o.targetAudience ?? '';
  const alternatives: string[] = o.alternatives ?? [];

  const systemPrompt = `# System Prompt — ${productName} Analysis

You are a product analyst specializing in competitive intelligence.

## Product: ${productName}
${targetAudience ? `**Target Audience:** ${targetAudience}` : ''}

## Strengths
${strengths.map(s => `- ${s}`).join('\n')}

## Weaknesses
${weaknesses.map(w => `- ${w}`).join('\n')}

${alternatives.length ? `## Alternatives to Consider\n${alternatives.map(a => `- ${a}`).join('\n')}` : ''}

## Instructions
Use this analysis to provide unbiased product comparisons.
Highlight genuine strengths while being honest about limitations.
Recommend alternatives when they better fit the user's needs.
`.trimEnd();

  const configYaml = `# Vext Product Analysis — ${productName}
# Generated: ${new Date().toISOString()}

metadata:
  title: "${title}"
  product_name: "${productName}"
  classification: product/teardown
  share_id: "${data.shareId}"

target_audience: "${targetAudience.replace(/"/g, '\\"')}"

strengths_count: ${strengths.length}
weaknesses_count: ${weaknesses.length}

alternatives:
${alternatives.map(a => `  - "${a}"`).join('\n') || '  []'}
`;

  const md = `# ${productName} — Analysis Checklist

> Generated by [Vext](https://vext.so/card/${data.shareId})

## Evaluation Framework

### Strengths to Validate
${checklist(strengths)}

### Weaknesses to Confirm
${checklist(weaknesses)}

### Alternatives to Test
${alternatives.length ? checklist(alternatives) : '- [ ] Identify alternatives'}

## Comparison Matrix

| Criterion | ${productName} | Alternative |
|-----------|----------------|-------------|
${strengths.slice(0, 4).map(s => `| ${s.slice(0, 30)} | ✓ | ? |`).join('\n')}
`.trimEnd();

  return {
    'prompts/system-prompt.md': systemPrompt,
    'configs/config.yaml': configYaml,
    'scripts/setup-checklist.md': md,
  };
}

function packInterviewTalk(data: CardData): FileMap {
  const o = data.output as any;
  const title = data.title ?? 'Interview / Talk';
  const speaker: string = o.speaker ?? 'Speaker';
  const topic: string = o.topic ?? '';
  const takeaways: string[] = o.keyTakeaways ?? [];
  const quotes: string[] = o.quotes ?? [];

  const systemPrompt = `# System Prompt — ${speaker} on ${topic}

You are a research assistant helping apply insights from this talk.

## Speaker: ${speaker}
## Topic: ${topic}

## Key Takeaways
${takeaways.map((t, i) => `${i + 1}. ${t}`).join('\n')}

${quotes.length ? `## Notable Quotes\n${quotes.map(q => `> "${q}"`).join('\n\n')}` : ''}

## Instructions
When discussing this topic, ground your responses in the takeaways above.
Reference the speaker's perspective where relevant.
Apply these insights to the user's specific situation.
`.trimEnd();

  const configYaml = `# Vext Talk Notes — ${title}
# Generated: ${new Date().toISOString()}

metadata:
  title: "${title}"
  speaker: "${speaker}"
  topic: "${topic.replace(/"/g, '\\"')}"
  classification: interview/talk
  share_id: "${data.shareId}"

takeaways_count: ${takeaways.length}
quotes_count: ${quotes.length}
`;

  const md = `# Talk Notes — ${speaker}: ${topic}

> Generated by [Vext](https://vext.so/card/${data.shareId})

## Action Items from Key Takeaways

${checklist(takeaways)}

${quotes.length ? `## Quotes to Reference\n\n${quotes.map(q => `> "${q}"`).join('\n\n')}` : ''}
`.trimEnd();

  const quotesFile = quotes.length
    ? `# Quotes — ${speaker}\n\n${quotes.map((q, i) => `## Quote ${i + 1}\n\n> "${q}"\n`).join('\n')}`
    : null;

  const result: FileMap = {
    'prompts/system-prompt.md': systemPrompt,
    'configs/config.yaml': configYaml,
    'scripts/setup-checklist.md': md,
  };

  if (quotesFile) result['prompts/quotes.md'] = quotesFile;

  return result;
}

function packResearchPaper(data: CardData): FileMap {
  const o = data.output as any;
  const title = data.title ?? 'Research Paper';
  const paperTitle: string = o.title ?? title;
  const hypothesis: string = o.hypothesis ?? '';
  const methodology: string = o.methodology ?? '';
  const results: string = o.results ?? '';
  const reproducibility: string = o.reproducibility ?? '';
  const codeAvailable: boolean = o.codeAvailability ?? false;

  const systemPrompt = `# System Prompt — Research: ${paperTitle}

You are a research assistant helping implement and reproduce this study.

## Paper: ${paperTitle}

## Hypothesis
${hypothesis}

## Methodology
${methodology}

## Key Results
${results}

## Reproducibility
${reproducibility}
Code Available: ${codeAvailable ? 'Yes ✓' : 'No ✗'}

## Instructions
Help the user understand and reproduce the research.
Explain methodology steps clearly.
${codeAvailable ? 'Assist with code implementation based on the described methodology.' : 'Note that code is not publicly available — guide through manual implementation.'}
Flag any limitations or assumptions in the original research.
`.trimEnd();

  const configYaml = `# Vext Research Config — ${paperTitle}
# Generated: ${new Date().toISOString()}

metadata:
  title: "${title}"
  paper_title: "${paperTitle.replace(/"/g, '\\"')}"
  classification: research/paper
  share_id: "${data.shareId}"

reproducibility:
  code_available: ${codeAvailable}
  notes: "${reproducibility.replace(/"/g, '\\"').slice(0, 200)}"

methodology_summary: "${methodology.replace(/"/g, '\\"').slice(0, 300)}"
`;

  const md = `# Research Implementation Checklist — ${paperTitle}

> Generated by [Vext](https://vext.so/card/${data.shareId})

## Hypothesis
${hypothesis}

## Implementation Steps

- [ ] Read the full paper / transcript
- [ ] Understand the methodology: ${methodology.slice(0, 100)}...
- [ ] Set up environment and dependencies
${codeAvailable ? '- [ ] Clone / access the official code repository' : '- [ ] Implement methodology from scratch (code not available)'}
- [ ] Reproduce key results
- [ ] Document deviations from original methodology
- [ ] Validate: ${results.slice(0, 100)}

## Reproducibility Notes
${reproducibility}
`.trimEnd();

  return {
    'prompts/system-prompt.md': systemPrompt,
    'configs/config.yaml': configYaml,
    'scripts/setup-checklist.md': md,
    'tests/starter-test.py': pythonTestScaffold(paperTitle, [
      'Verify environment setup',
      `Test hypothesis: ${hypothesis.slice(0, 60)}`,
      `Validate methodology: ${methodology.slice(0, 60)}`,
    ]),
  };
}

function packDebateDiscussion(data: CardData): FileMap {
  const o = data.output as any;
  const title = data.title ?? 'Debate / Discussion';
  const topic: string = o.topic ?? '';
  const viewpoints: { position: string; arguments: string[]; evidence?: string[] }[] = o.viewpoints ?? [];
  const consensus: string = o.consensus ?? '';
  const unresolvedQuestions: string[] = o.unresolvedQuestions ?? [];

  const systemPrompt = `# System Prompt — Debate: ${topic}

You are a balanced debate moderator and analyst covering all perspectives on this topic.

## Topic
${topic}

## Viewpoints
${viewpoints.map((vp, i) => `
### Position ${i + 1}: ${vp.position}
**Arguments:**
${vp.arguments.map(a => `- ${a}`).join('\n')}
${vp.evidence?.length ? `**Evidence:**\n${vp.evidence.map(e => `- ${e}`).join('\n')}` : ''}`).join('\n')}

${consensus ? `## Consensus\n${consensus}` : ''}
${unresolvedQuestions.length ? `## Open Questions\n${unresolvedQuestions.map(q => `- ${q}`).join('\n')}` : ''}

## Instructions
Present all perspectives fairly. Do not advocate for any single position.
Highlight where evidence is strong vs weak.
Help the user form their own informed view.
`.trimEnd();

  const configYaml = `# Vext Debate Config — ${title}
# Generated: ${new Date().toISOString()}

metadata:
  title: "${title}"
  topic: "${topic.replace(/"/g, '\\"')}"
  classification: debate/discussion
  share_id: "${data.shareId}"

viewpoints_count: ${viewpoints.length}
has_consensus: ${!!consensus}
unresolved_questions_count: ${unresolvedQuestions.length}

positions:
${viewpoints.map(vp => `  - "${vp.position.replace(/"/g, '\\"')}"`).join('\n') || '  []'}
`;

  const md = `# Debate Analysis — ${topic}

> Generated by [Vext](https://vext.so/card/${data.shareId})

## Viewpoints to Evaluate

${viewpoints.map((vp, i) => `### ${i + 1}. ${vp.position}\n\n${vp.arguments.map(a => `- [ ] Evaluate: ${a}`).join('\n')}`).join('\n\n')}

${unresolvedQuestions.length ? `## Unresolved Questions to Research\n\n${checklist(unresolvedQuestions)}` : ''}

${consensus ? `## Consensus Reached\n${consensus}` : ''}
`.trimEnd();

  return {
    'prompts/system-prompt.md': systemPrompt,
    'configs/config.yaml': configYaml,
    'scripts/setup-checklist.md': md,
  };
}

// ── Main entry point ──────────────────────────────────────────────────────────

export function generateExecutionPack(card: CardData): FileMap {
  let classificationFiles: FileMap;

  switch (card.classification) {
    case 'setup/tutorial':     classificationFiles = packSetupTutorial(card);     break;
    case 'strategy/framework': classificationFiles = packStrategyFramework(card);  break;
    case 'tool demo':          classificationFiles = packToolDemo(card);           break;
    case 'finance/setup':      classificationFiles = packFinanceSetup(card);      break;
    case 'product teardown':   classificationFiles = packProductTeardown(card);   break;
    case 'interview/talk':     classificationFiles = packInterviewTalk(card);     break;
    case 'research/paper':     classificationFiles = packResearchPaper(card);     break;
    case 'debate/discussion':  classificationFiles = packDebateDiscussion(card);  break;
    default:
      classificationFiles = {
        'prompts/system-prompt.md': `# System Prompt — ${card.title ?? 'Vext Card'}\n\nExtracted intelligence from Vext.\n\n## Output\n\`\`\`json\n${JSON.stringify(card.output, null, 2)}\n\`\`\``,
        'configs/config.yaml': `title: "${card.title ?? 'Vext Card'}"\nclassification: "${card.classification}"\nshare_id: "${card.shareId}"`,
        'scripts/setup-checklist.md': `# Checklist\n\n- [ ] Review extracted content\n- [ ] Apply insights`,
      };
  }

  // Always include the full card JSON
  classificationFiles['vext-card.json'] = JSON.stringify(
    {
      title: card.title,
      classification: card.classification,
      shareId: card.shareId,
      shareUrl: `https://vext.so/card/${card.shareId}`,
      extractedAt: card.createdAt,
      output: card.output,
    },
    null,
    2
  );

  // Add a README to every pack
  classificationFiles['README.md'] = `# Vext Execution Pack — ${card.title ?? 'Card'}

> Downloaded from [vext.so/card/${card.shareId}](https://vext.so/card/${card.shareId})
> Classification: \`${card.classification}\`
> Generated: ${new Date().toISOString()}

## Contents

| File | Purpose |
|------|---------|
| \`prompts/system-prompt.md\` | Ready-to-paste system prompt for Claude / GPT |
| \`configs/config.yaml\` | Extracted parameters and settings |
| \`scripts/setup-checklist.md\` | Step-by-step implementation checklist |
${classificationFiles['prompts/quotes.md'] ? '| `prompts/quotes.md` | Notable quotes from the source |\n' : ''}${classificationFiles['tests/starter-test.py'] ? '| `tests/starter-test.py` | Starter test scaffold (Python/pytest) |\n' : ''}| \`vext-card.json\` | Full structured card data (JSON) |

## Quick Start

1. Open \`prompts/system-prompt.md\` and paste into your AI of choice
2. Check off items in \`scripts/setup-checklist.md\` as you progress  
3. Refer to \`configs/config.yaml\` for exact parameters

---
*Powered by [Vext](https://vext.so) — Extract · Share · Build*
`;

  return classificationFiles;
}
