/**
 * generateExecutionPack — maps card output fields to a zip-ready file map.
 * Returns Record<path, utf-8 string content>
 */

import { generateManifest } from './manifest';
import { extractKeyConcepts } from './concepts';

export interface CardData {
  shareId: string;
  title: string | null;
  classification: string;
  output: unknown;
  createdAt: Date;
}

// ── Simple YAML serialiser (handles 1-level nesting) ─────────────────────────
function toYaml(obj: Record<string, unknown>, indent = 0): string {
  const pad = '  '.repeat(indent);
  return Object.entries(obj)
    .map(([k, v]) => {
      if (v == null) return `${pad}${k}: ~`;
      if (typeof v === 'object' && !Array.isArray(v)) {
        return `${pad}${k}:\n${toYaml(v as Record<string, unknown>, indent + 1)}`;
      }
      if (Array.isArray(v)) {
        const items = (v as unknown[]).map(i => `${pad}  - ${String(i)}`).join('\n');
        return `${pad}${k}:\n${items}`;
      }
      // Quote strings that need it
      const s = String(v);
      const needsQuote = s.includes(':') || s.includes('#') || s.includes('\n') || s.includes('"');
      return `${pad}${k}: ${needsQuote ? `"${s.replace(/"/g, '\\"')}"` : s}`;
    })
    .join('\n');
}

// ── Checklist builder ─────────────────────────────────────────────────────────
function checklist(items: string[], header = ''): string {
  const lines = items.map(item => `- [ ] ${item}`).join('\n');
  return header ? `${header}\n\n${lines}` : lines;
}

// ── Python test scaffold ──────────────────────────────────────────────────────
function pythonTestScaffold(title: string, steps: string[]): string {
  const testFns = steps.slice(0, 3).map((step, i) => {
    const name = step.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '_').toLowerCase().slice(0, 40) || `step_${i + 1}`;
    return `def test_${name}():\n    # TODO: implement test for: ${step}\n    pass`;
  });

  return `"""
Starter tests for: ${title}
Generated by Vext — https://vext.so
"""

import pytest


${testFns.join('\n\n')}


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
`;
}

// ── Per-classification file generators ───────────────────────────────────────

type FileMap = Record<string, string>;

function packSetupTutorial(data: CardData): FileMap {
  const o = data.output as any;
  const title = data.title ?? 'Setup Tutorial';
  const steps: string[] = o.steps ?? [];
  const snippets: Record<string, string> = o.configSnippets ?? {};
  const files: string[] = o.generatedFiles ?? [];

  const systemPrompt = `# System Prompt — ${title}

You are an expert assistant helping implement the following setup/tutorial exactly as described.

## Your Role
Guide the user through each step precisely. If they get stuck, refer to the numbered steps below.
Do not skip steps. Confirm completion before moving to the next.

## Steps to Follow
${steps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

${files.length ? `## Files to Create/Modify\n${files.map(f => `- \`${f}\``).join('\n')}` : ''}

## Rules
- Follow steps in order.
- Use exact config values provided.
- Ask clarifying questions only if a step is ambiguous.
- Confirm each step is complete before proceeding.
`.trimEnd();

  const configYaml = `# Vext Config — ${title}
# Generated: ${new Date().toISOString()}

metadata:
  title: "${title}"
  classification: setup/tutorial
  share_id: "${data.shareId}"

${Object.keys(snippets).length > 0 ? `config_snippets:\n${Object.entries(snippets).map(([k, v]) => `  ${k}: |\n    ${v.replace(/\n/g, '\n    ')}`).join('\n')}` : '# No config snippets extracted'}

generated_files:
${files.length ? files.map(f => `  - "${f}"`).join('\n') : '  []'}
`;

  const md = `# Setup Checklist — ${title}

> Generated by [Vext](https://vext.so/card/${data.shareId}) on ${new Date().toLocaleDateString()}

## Steps

${checklist(steps)}

${files.length ? `## Files to Create\n\n${files.map(f => `- [ ] \`${f}\``).join('\n')}` : ''}
`.trimEnd();

  const files_map: FileMap = {
    'prompts/system-prompt.md': systemPrompt,
    'configs/config.yaml': configYaml,
    'scripts/setup-checklist.md': md,
  };

  if (Object.keys(snippets).length > 0) {
    files_map['tests/starter-test.py'] = pythonTestScaffold(title, steps);
  }

  return files_map;
}

function packStrategyFramework(data: CardData): FileMap {
  const o = data.output as any;
  const title = data.title ?? 'Strategy Framework';
  const methodology: string = o.methodology ?? '';
  const principles: string[] = o.keyPrinciples ?? [];
  const frameworks: string[] = o.frameworks ?? [];
  const decisionTree: string = o.decisionTree ?? '';

  const systemPrompt = `# System Prompt — ${title}

You are a strategic advisor helping implement the following framework.

## Methodology
${methodology}

## Key Principles
${principles.map((p, i) => `${i + 1}. ${p}`).join('\n')}

${decisionTree ? `## Decision Tree\n${decisionTree}` : ''}

${frameworks.length ? `## Referenced Frameworks\n${frameworks.map(f => `- ${f}`).join('\n')}` : ''}

## Instructions
When advising, always ground recommendations in the principles above.
Present trade-offs clearly and map decisions to the framework.
`.trimEnd();

  const configYaml = `# Vext Config — ${title}
# Generated: ${new Date().toISOString()}

metadata:
  title: "${title}"
  classification: strategy/framework
  share_id: "${data.shareId}"

methodology: "${methodology.replace(/"/g, '\\"')}"

key_principles:
${principles.map(p => `  - "${p.replace(/"/g, '\\"')}"`).join('\n') || '  []'}

related_frameworks:
${frameworks.map(f => `  - "${f}"`).join('\n') || '  []'}
`;

  const md = `# Strategy Checklist — ${title}

> Generated by [Vext](https://vext.so/card/${data.shareId})

## Methodology
${methodology}

## Implementation Checklist

${checklist(principles)}

${frameworks.length ? `## Frameworks to Study\n\n${frameworks.map(f => `- [ ] ${f}`).join('\n')}` : ''}
`.trimEnd();

  return {
    'prompts/system-prompt.md': systemPrompt,
    'configs/config.yaml': configYaml,
    'scripts/setup-checklist.md': md,
  };
}

function packToolDemo(data: CardData): FileMap {
  const o = data.output as any;
  const title = data.title ?? 'Tool Demo';
  const toolName: string = o.toolName ?? 'Tool';
  const features: string[] = o.features ?? [];
  const useCases: string[] = o.useCases ?? [];
  const pros: string[] = o.prosCons?.pros ?? [];
  const cons: string[] = o.prosCons?.cons ?? [];

  const systemPrompt = `# System Prompt — ${title}

You are an expert on ${toolName}. Help the user understand and use it effectively.

## Tool: ${toolName}

## Key Features
${features.map(f => `- ${f}`).join('\n')}

## Primary Use Cases
${useCases.map((u, i) => `${i + 1}. ${u}`).join('\n')}

## Strengths & Limitations
**Strengths:** ${pros.join(', ')}
**Limitations:** ${cons.join(', ')}

## Instructions
Provide concrete examples for each feature. Always acknowledge limitations honestly.
Recommend ${toolName} only when it genuinely fits the use case.
`.trimEnd();

  const configYaml = `# Vext Config — ${toolName} Demo
# Generated: ${new Date().toISOString()}

metadata:
  title: "${title}"
  classification: tool/demo
  tool_name: "${toolName}"
  share_id: "${data.shareId}"

evaluation:
  pros:
${pros.map(p => `    - "${p.replace(/"/g, '\\"')}"`).join('\n') || '    []'}
  cons:
${cons.map(c => `    - "${c.replace(/"/g, '\\"')}"`).join('\n') || '    []'}

use_cases:
${useCases.map(u => `  - "${u.replace(/"/g, '\\"')}"`).join('\n') || '  []'}
`;

  const md = `# ${toolName} Evaluation Checklist

> Generated by [Vext](https://vext.so/card/${data.shareId})

## Features to Test

${checklist(features)}

## Use Cases to Validate

${checklist(useCases)}

## Pros vs Cons

| Pros | Cons |
|------|------|
${Math.max(pros.length, cons.length) > 0
    ? Array.from({ length: Math.max(pros.length, cons.length) })
        .map((_, i) => `| ${pros[i] ?? ''} | ${cons[i] ?? ''} |`)
        .join('\n')
    : '| — | — |'}
`.trimEnd();

  return {
    'prompts/system-prompt.md': systemPrompt,
    'configs/config.yaml': configYaml,
    'scripts/setup-checklist.md': md,
    'tests/starter-test.py': pythonTestScaffold(toolName, features),
  };
}

function packFinanceSetup(data: CardData): FileMap {
  const o = data.output as any;
  const title = data.title ?? 'Finance Setup';
  const strategy: string = o.strategy ?? '';
  const riskParams: Record<string, string> = o.riskParameters ?? {};
  const backtest = o.backtestResults ?? {};
  const snippets: Record<string, string> = o.configSnippets ?? {};

  const systemPrompt = `# System Prompt — ${title}

You are a quantitative trading assistant implementing the following strategy.

## Strategy
${strategy}

## Risk Parameters
${Object.entries(riskParams).map(([k, v]) => `- **${k}**: ${v}`).join('\n')}

${backtest && Object.keys(backtest).length
    ? `## Backtest Performance\n${[
        backtest.sharpeRatio != null ? `- Sharpe Ratio: ${backtest.sharpeRatio}` : '',
        backtest.maxDrawdown != null ? `- Max Drawdown: ${backtest.maxDrawdown}%` : '',
        backtest.winRate != null ? `- Win Rate: ${backtest.winRate}%` : '',
      ].filter(Boolean).join('\n')}`
    : ''}

## Instructions
Implement trades ONLY within the defined risk parameters.
Always confirm current market conditions before execution.
Never override the risk limits. Log all decisions with rationale.

## ⚠️ Disclaimer
This is educational content only — not financial advice.
`.trimEnd();

  const configYaml = `# Vext Finance Config — ${title}
# Generated: ${new Date().toISOString()}
# ⚠️ DISCLAIMER: Educational only. Not financial advice.

metadata:
  title: "${title}"
  classification: finance/setup
  share_id: "${data.shareId}"

strategy:
  description: "${strategy.replace(/"/g, '\\"').slice(0, 200)}"

risk_parameters:
${Object.entries(riskParams).map(([k, v]) => `  ${k}: "${v}"`).join('\n') || '  {}'}

backtest_results:
${backtest.sharpeRatio != null ? `  sharpe_ratio: ${backtest.sharpeRatio}` : '  sharpe_ratio: ~'}
${backtest.maxDrawdown != null ? `  max_drawdown_pct: ${backtest.maxDrawdown}` : '  max_drawdown_pct: ~'}
${backtest.winRate != null ? `  win_rate_pct: ${backtest.winRate}` : '  win_rate_pct: ~'}

${Object.keys(snippets).length ? `config_snippets:\n${Object.entries(snippets).map(([k, v]) => `  ${k}: |\n    ${v.replace(/\n/g, '\n    ')}`).join('\n')}` : ''}
`;

  const md = `# Finance Setup Checklist — ${title}

> Generated by [Vext](https://vext.so/card/${data.shareId})
> ⚠️ Educational purposes only — not financial advice.

## Strategy Overview
${strategy}

## Pre-Trade Checklist

- [ ] Verify all risk parameters are configured
- [ ] Confirm backtesting is complete
- [ ] Paper trade for minimum 2 weeks
- [ ] Set stop-loss levels per risk params
- [ ] Define position sizing rules
- [ ] Configure alerts and monitoring

## Risk Parameters

${Object.entries(riskParams).map(([k, v]) => `- [ ] **${k}**: ${v}`).join('\n') || '- [ ] Define risk parameters'}
`.trimEnd();

  return {
    'prompts/system-prompt.md': systemPrompt,
    'configs/config.yaml': configYaml,
    'scripts/setup-checklist.md': md,
    'tests/starter-test.py': pythonTestScaffold(title, Object.keys(riskParams).map(k => `Validate ${k} = ${riskParams[k]}`)),
  };
}

function packProductTeardown(data: CardData): FileMap {
  const o = data.output as any;
  const title = data.title ?? 'Product Teardown';
  const productName: string = o.productName ?? 'Product';
  const strengths: string[] = o.strengths ?? [];
  const weaknesses: string[] = o.weaknesses ?? [];
  const targetAudience: string = o.targetAudience ?? '';
  const alternatives: string[] = o.alternatives ?? [];

  const systemPrompt = `# System Prompt — ${productName} Analysis

You are a product analyst specializing in competitive intelligence.

## Product: ${productName}
${targetAudience ? `**Target Audience:** ${targetAudience}` : ''}

## Strengths
${strengths.map(s => `- ${s}`).join('\n')}

## Weaknesses
${weaknesses.map(w => `- ${w}`).join('\n')}

${alternatives.length ? `## Alternatives to Consider\n${alternatives.map(a => `- ${a}`).join('\n')}` : ''}

## Instructions
Use this analysis to provide unbiased product comparisons.
Highlight genuine strengths while being honest about limitations.
Recommend alternatives when they better fit the user's needs.
`.trimEnd();

  const configYaml = `# Vext Product Analysis — ${productName}
# Generated: ${new Date().toISOString()}

metadata:
  title: "${title}"
  product_name: "${productName}"
  classification: product/teardown
  share_id: "${data.shareId}"

target_audience: "${targetAudience.replace(/"/g, '\\"')}"

strengths_count: ${strengths.length}
weaknesses_count: ${weaknesses.length}

alternatives:
${alternatives.map(a => `  - "${a}"`).join('\n') || '  []'}
`;

  const md = `# ${productName} — Analysis Checklist

> Generated by [Vext](https://vext.so/card/${data.shareId})

## Evaluation Framework

### Strengths to Validate
${checklist(strengths)}

### Weaknesses to Confirm
${checklist(weaknesses)}

### Alternatives to Test
${alternatives.length ? checklist(alternatives) : '- [ ] Identify alternatives'}

## Comparison Matrix

| Criterion | ${productName} | Alternative |
|-----------|----------------|-------------|
${strengths.slice(0, 4).map(s => `| ${s.slice(0, 30)} | ✓ | ? |`).join('\n')}
`.trimEnd();

  return {
    'prompts/system-prompt.md': systemPrompt,
    'configs/config.yaml': configYaml,
    'scripts/setup-checklist.md': md,
  };
}

function packInterviewTalk(data: CardData): FileMap {
  const o = data.output as any;
  const title = data.title ?? 'Interview / Talk';
  const speaker: string = o.speaker ?? 'Speaker';
  const topic: string = o.topic ?? '';
  const takeaways: string[] = o.keyTakeaways ?? [];
  const quotes: string[] = o.quotes ?? [];

  const systemPrompt = `# System Prompt — ${speaker} on ${topic}

You are a research assistant helping apply insights from this talk.

## Speaker: ${speaker}
## Topic: ${topic}

## Key Takeaways
${takeaways.map((t, i) => `${i + 1}. ${t}`).join('\n')}

${quotes.length ? `## Notable Quotes\n${quotes.map(q => `> "${q}"`).join('\n\n')}` : ''}

## Instructions
When discussing this topic, ground your responses in the takeaways above.
Reference the speaker's perspective where relevant.
Apply these insights to the user's specific situation.
`.trimEnd();

  const configYaml = `# Vext Talk Notes — ${title}
# Generated: ${new Date().toISOString()}

metadata:
  title: "${title}"
  speaker: "${speaker}"
  topic: "${topic.replace(/"/g, '\\"')}"
  classification: interview/talk
  share_id: "${data.shareId}"

takeaways_count: ${takeaways.length}
quotes_count: ${quotes.length}
`;

  const md = `# Talk Notes — ${speaker}: ${topic}

> Generated by [Vext](https://vext.so/card/${data.shareId})

## Action Items from Key Takeaways

${checklist(takeaways)}

${quotes.length ? `## Quotes to Reference\n\n${quotes.map(q => `> "${q}"`).join('\n\n')}` : ''}
`.trimEnd();

  const quotesFile = quotes.length
    ? `# Quotes — ${speaker}\n\n${quotes.map((q, i) => `## Quote ${i + 1}\n\n> "${q}"\n`).join('\n')}`
    : null;

  const result: FileMap = {
    'prompts/system-prompt.md': systemPrompt,
    'configs/config.yaml': configYaml,
    'scripts/setup-checklist.md': md,
  };

  if (quotesFile) result['prompts/quotes.md'] = quotesFile;

  return result;
}

function packResearchPaper(data: CardData): FileMap {
  const o = data.output as any;
  const title = data.title ?? 'Research Paper';
  const paperTitle: string = o.title ?? title;
  const hypothesis: string = o.hypothesis ?? '';
  const methodology: string = o.methodology ?? '';
  const results: string = o.results ?? '';
  const reproducibility: string = o.reproducibility ?? '';
  const codeAvailable: boolean = o.codeAvailability ?? false;

  const systemPrompt = `# System Prompt — Research: ${paperTitle}

You are a research assistant helping implement and reproduce this study.

## Paper: ${paperTitle}

## Hypothesis
${hypothesis}

## Methodology
${methodology}

## Key Results
${results}

## Reproducibility
${reproducibility}
Code Available: ${codeAvailable ? 'Yes ✓' : 'No ✗'}

## Instructions
Help the user understand and reproduce the research.
Explain methodology steps clearly.
${codeAvailable ? 'Assist with code implementation based on the described methodology.' : 'Note that code is not publicly available — guide through manual implementation.'}
Flag any limitations or assumptions in the original research.
`.trimEnd();

  const configYaml = `# Vext Research Config — ${paperTitle}
# Generated: ${new Date().toISOString()}

metadata:
  title: "${title}"
  paper_title: "${paperTitle.replace(/"/g, '\\"')}"
  classification: research/paper
  share_id: "${data.shareId}"

reproducibility:
  code_available: ${codeAvailable}
  notes: "${reproducibility.replace(/"/g, '\\"').slice(0, 200)}"

methodology_summary: "${methodology.replace(/"/g, '\\"').slice(0, 300)}"
`;

  const md = `# Research Implementation Checklist — ${paperTitle}

> Generated by [Vext](https://vext.so/card/${data.shareId})

## Hypothesis
${hypothesis}

## Implementation Steps

- [ ] Read the full paper / transcript
- [ ] Understand the methodology: ${methodology.slice(0, 100)}...
- [ ] Set up environment and dependencies
${codeAvailable ? '- [ ] Clone / access the official code repository' : '- [ ] Implement methodology from scratch (code not available)'}
- [ ] Reproduce key results
- [ ] Document deviations from original methodology
- [ ] Validate: ${results.slice(0, 100)}

## Reproducibility Notes
${reproducibility}
`.trimEnd();

  return {
    'prompts/system-prompt.md': systemPrompt,
    'configs/config.yaml': configYaml,
    'scripts/setup-checklist.md': md,
    'tests/starter-test.py': pythonTestScaffold(paperTitle, [
      'Verify environment setup',
      `Test hypothesis: ${hypothesis.slice(0, 60)}`,
      `Validate methodology: ${methodology.slice(0, 60)}`,
    ]),
  };
}

function packDebateDiscussion(data: CardData): FileMap {
  const o = data.output as any;
  const title = data.title ?? 'Debate / Discussion';
  const topic: string = o.topic ?? '';
  const viewpoints: { position: string; arguments: string[]; evidence?: string[] }[] = o.viewpoints ?? [];
  const consensus: string = o.consensus ?? '';
  const unresolvedQuestions: string[] = o.unresolvedQuestions ?? [];

  const systemPrompt = `# System Prompt — Debate: ${topic}

You are a balanced debate moderator and analyst covering all perspectives on this topic.

## Topic
${topic}

## Viewpoints
${viewpoints.map((vp, i) => `
### Position ${i + 1}: ${vp.position}
**Arguments:**
${vp.arguments.map(a => `- ${a}`).join('\n')}
${vp.evidence?.length ? `**Evidence:**\n${vp.evidence.map(e => `- ${e}`).join('\n')}` : ''}`).join('\n')}

${consensus ? `## Consensus\n${consensus}` : ''}
${unresolvedQuestions.length ? `## Open Questions\n${unresolvedQuestions.map(q => `- ${q}`).join('\n')}` : ''}

## Instructions
Present all perspectives fairly. Do not advocate for any single position.
Highlight where evidence is strong vs weak.
Help the user form their own informed view.
`.trimEnd();

  const configYaml = `# Vext Debate Config — ${title}
# Generated: ${new Date().toISOString()}

metadata:
  title: "${title}"
  topic: "${topic.replace(/"/g, '\\"')}"
  classification: debate/discussion
  share_id: "${data.shareId}"

viewpoints_count: ${viewpoints.length}
has_consensus: ${!!consensus}
unresolved_questions_count: ${unresolvedQuestions.length}

positions:
${viewpoints.map(vp => `  - "${vp.position.replace(/"/g, '\\"')}"`).join('\n') || '  []'}
`;

  const md = `# Debate Analysis — ${topic}

> Generated by [Vext](https://vext.so/card/${data.shareId})

## Viewpoints to Evaluate

${viewpoints.map((vp, i) => `### ${i + 1}. ${vp.position}\n\n${vp.arguments.map(a => `- [ ] Evaluate: ${a}`).join('\n')}`).join('\n\n')}

${unresolvedQuestions.length ? `## Unresolved Questions to Research\n\n${checklist(unresolvedQuestions)}` : ''}

${consensus ? `## Consensus Reached\n${consensus}` : ''}
`.trimEnd();

  return {
    'prompts/system-prompt.md': systemPrompt,
    'configs/config.yaml': configYaml,
    'scripts/setup-checklist.md': md,
  };
}

// ── Main entry point ──────────────────────────────────────────────────────────

export function generateExecutionPack(card: CardData): FileMap {
  let classificationFiles: FileMap;

  switch (card.classification) {
    case 'setup/tutorial':     classificationFiles = packSetupTutorial(card);     break;
    case 'strategy/framework': classificationFiles = packStrategyFramework(card);  break;
    case 'tool demo':          classificationFiles = packToolDemo(card);           break;
    case 'finance/setup':      classificationFiles = packFinanceSetup(card);      break;
    case 'product teardown':   classificationFiles = packProductTeardown(card);   break;
    case 'interview/talk':     classificationFiles = packInterviewTalk(card);     break;
    case 'research/paper':     classificationFiles = packResearchPaper(card);     break;
    case 'debate/discussion':  classificationFiles = packDebateDiscussion(card);  break;
    default:
      classificationFiles = {
        'prompts/system-prompt.md': `# System Prompt — ${card.title ?? 'Vext Card'}\n\nExtracted intelligence from Vext.\n\n## Output\n\`\`\`json\n${JSON.stringify(card.output, null, 2)}\n\`\`\``,
        'configs/config.yaml': `title: "${card.title ?? 'Vext Card'}"\nclassification: "${card.classification}"\nshare_id: "${card.shareId}"`,
        'scripts/setup-checklist.md': `# Checklist\n\n- [ ] Review extracted content\n- [ ] Apply insights`,
      };
  }

  // Always include the full card JSON
  classificationFiles['vext-card.json'] = JSON.stringify(
    {
      title: card.title,
      classification: card.classification,
      shareId: card.shareId,
      shareUrl: `https://vext.so/card/${card.shareId}`,
      extractedAt: card.createdAt,
      output: card.output,
    },
    null,
    2
  );

  // Add enhanced files
  const enhancedFiles = generateEnhancedFiles(card);
  Object.assign(classificationFiles, enhancedFiles);

  // Add a README to every pack
  classificationFiles['README.md'] = `# Vext Execution Pack — ${card.title ?? 'Card'}

> Downloaded from [vext.so/card/${card.shareId}](https://vext.so/card/${card.shareId})
> Classification: \`${card.classification}\`
> Generated: ${new Date().toISOString()}

## Contents

| File | Purpose |
|------|---------|
| \`manifest.json\` | Project metadata and tech stack |
| \`SYSTEM_PROMPT.md\` | Agent instructions to recreate the project |
| \`SETUP_GUIDE.md\` | Prerequisites and environment setup |
| \`BUILD_PLAN.md\` | Ordered tasks with verification steps |
| \`CODE_SNIPPETS.json\` | Extracted code with context |
| \`KEY_CONCEPTS.json\` | Explained technical concepts |
| \`prompts/system-prompt.md\` | Original extraction system prompt |
| \`configs/config.yaml\` | Extracted parameters and settings |
| \`scripts/setup-checklist.md\` | Step-by-step implementation checklist |
${classificationFiles['prompts/quotes.md'] ? '| `prompts/quotes.md` | Notable quotes from the source |\n' : ''}${classificationFiles['tests/starter-test.py'] ? '| `tests/starter-test.py` | Starter test scaffold (Python/pytest) |\n' : ''}| \`vext-card.json\` | Full structured card data (JSON) |

## Quick Start

1. Read \`SETUP_GUIDE.md\` for prerequisites
2. Follow tasks in \`BUILD_PLAN.md\` in order
3. Use \`SYSTEM_PROMPT.md\` to bootstrap an AI agent
4. Reference \`CODE_SNIPPETS.json\` for implementation details

---
*Powered by [Vext](https://vext.so) — Extract · Share · Build*
`;

  return classificationFiles;
}

function generateEnhancedFiles(card: CardData): FileMap {
  const o = card.output as Record<string, unknown>;
  const title = card.title ?? 'Untitled Project';

  const manifest = generateManifest(card);
  const concepts = extractKeyConcepts(JSON.stringify(o));

  const systemPrompt = generateSystemPrompt(title, o, card.classification);
  const setupGuide = generateSetupGuide(title, o, card.classification);
  const buildPlan = generateBuildPlan(title, o, card.classification);
  const codeSnippets = extractCodeSnippets(o);

  return {
    'manifest.json': JSON.stringify(manifest, null, 2),
    'SYSTEM_PROMPT.md': systemPrompt,
    'SETUP_GUIDE.md': setupGuide,
    'BUILD_PLAN.md': buildPlan,
    'CODE_SNIPPETS.json': JSON.stringify(codeSnippets, null, 2),
    'KEY_CONCEPTS.json': JSON.stringify(concepts, null, 2),
  };
}

function generateSystemPrompt(title: string, output: Record<string, unknown>, classification: string): string {
  const stack = output.recommended_stack as string[] || [];
  const starterCode = output.starter_code_snippet as string || '';
  const prompts = output.prompts_to_generate as Array<{system_prompt_text: string; user_prompt_template: string}> || [];

  return `# System Prompt — ${title}

You are an expert software engineer tasked with building the project described below.

## Project Overview
- **Name**: ${title}
- **Classification**: ${classification}
- **Created**: ${new Date().toISOString()}

## Goal
Build a complete, production-ready implementation based on the extracted knowledge from video tutorials.

## Recommended Tech Stack
${stack.length > 0 ? stack.map(t => `- ${t}`).join('\n') : '- Not specified (use appropriate tools for the task)'}

## Core Problem to Solve
${output.core_opportunity ? `**Problem**: ${(output.core_opportunity as Record<string, unknown>)?.problem_statement || 'See project description'}`
  : 'Implement the project as described in the tutorial.'}

## Key Requirements
${output.business_model ? `**Business Model**: ${((output.business_model as Record<string, unknown>)?.revenue_streams as string[])?.join(', ') || 'N/A'}`
  : ''}

## Suggested Approach
${prompts.length > 0 ? prompts.map((p, i) => `${i + 1}. Use system prompt: "${p.system_prompt_text.slice(0, 100)}..."`).join('\n') : 'Follow the build plan for step-by-step implementation.'}

${starterCode ? `## Starter Code Reference
\`\`\`\n${starterCode}\n\`\`\`` : ''}

## Instructions
1. Analyze the SETUP_GUIDE.md for prerequisites
2. Follow BUILD_PLAN.md tasks in order
3. Implement each step completely before moving on
4. Write tests for core functionality
5. Verify the implementation matches the original tutorial intent

Remember: The goal is to create a working project, not just understand the tutorial.
`;
}

function generateSetupGuide(title: string, output: Record<string, unknown>, classification: string): string {
  const stack = output.recommended_stack as string[] || [];
  const apis = output.external_apis as string[] || [];

  return `# Setup Guide — ${title}

> Prerequisites and environment setup for building this project.

## Prerequisites

### Required Tools
${stack.length > 0 ? stack.map(t => `- ${getToolRequirement(t)}`).join('\n') : '- See project-specific requirements below'}

### Accounts & Access
${apis.length > 0 ? apis.map(api => `- ${api}: Create account at official website`).join('\n') : ''}

### Environment Variables
Create a \`.env\` file in the project root:

\`\`\`env
# Required
DATABASE_URL=postgresql://localhost:5432/project_db
API_KEY=your_api_key_here

# Optional
DEBUG=true
LOG_LEVEL=info
\`\`\`

## Installation Steps

1. **Clone/Fork the base project**
   \`\`\`bash
   git clone <repository-url>
   cd <project-name>
   \`\`\`

2. **Install dependencies**
   \`\`\`bash
   npm install  # or pip install -r requirements.txt for Python
   \`\`\`

3. **Configure environment**
   \`\`\`bash
   cp .env.example .env
   # Edit .env with your values
   \`\`\`

4. **Set up the database**
   \`\`\`bash
   # Run migrations
   npm run db:migrate  # or flask db upgrade / alembic upgrade
   \`\`\`

5. **Verify setup**
   \`\`\`bash
   npm run dev  # or python manage.py runserver
   # Visit http://localhost:3000 (or 5000 for Python)
   \`\`\`

## Troubleshooting

- **Database connection errors**: Ensure PostgreSQL is running and DATABASE_URL is correct
- **API key errors**: Double-check environment variables are set
- **Port conflicts**: Change port in config or kill existing process

---
*Generated by Vext — vext.so*
`;
}

function generateBuildPlan(title: string, output: Record<string, unknown>, classification: string): string {
  const roadmap = output.execution_roadmap as Record<string, string[]> | undefined;
  const blueprint = output.technical_blueprint as Record<string, unknown> | undefined;
  const dataModel = blueprint?.data_model as {tables_or_collections?: string[]; key_relationships?: string} | undefined;

  const steps: string[] = [];
  
  if (roadmap) {
    if (roadmap.month_1_mvp) steps.push(...roadmap.month_1_mvp.map(s => `Month 1: ${s}`));
    if (roadmap.month_2_traction) steps.push(...roadmap.month_2_traction.map(s => `Month 2: ${s}`));
    if (roadmap.month_3_scale) steps.push(...roadmap.month_3_scale.map(s => `Month 3: ${s}`));
  }

  if (steps.length === 0) {
    steps.push(
      'Set up development environment',
      'Create database schema and models',
      'Implement core functionality',
      'Add API endpoints',
      'Build frontend interface',
      'Write tests',
      'Deploy to production'
    );
  }

  return `# Build Plan — ${title}

> Ordered tasks for implementing this project. Complete each step before moving to the next.

## Project: ${title}
> Classification: ${classification}

## Implementation Phases

${steps.map((step, i) => `${i + 1}. [ ] ${step}`).join('\n')}

## Data Model

${dataModel ? `### Tables/Collections
${(dataModel.tables_or_collections || []).map(t => `- \`${t}\``).join('\n')}

### Relationships
${dataModel.key_relationships || 'Not specified'}` : 'Data model not explicitly specified in this extraction.'}

## Verification Steps

After completing each phase, verify:
- [ ] Code compiles/runs without errors
- [ ] Tests pass
- [ ] No console errors in browser/dev tools
- [ ] API endpoints return expected responses

## Success Criteria

The project is complete when:
- [ ] All core features from the tutorial are implemented
- [ ] Application runs locally without errors
- [ ] Basic tests pass
- [ ] Documentation is updated

---
*Generated by Vext — vext.so*
`;
}

function extractCodeSnippets(output: Record<string, unknown>): Array<{file: string; code: string; context: string}> {
  const snippets: Array<{file: string; code: string; context: string}> = [];
  
  const starterCode = output.starter_code_snippet as string;
  if (starterCode) {
    snippets.push({
      file: 'src/main.py', // or appropriate extension
      code: starterCode,
      context: 'Core implementation from the tutorial',
    });
  }

  const generatedFiles = (output.generated_files as Record<string, Array<{filename: string; content: string}>> | undefined);
  if (generatedFiles?.scripts) {
    for (const script of generatedFiles.scripts) {
      snippets.push({
        file: script.filename,
        code: script.content,
        context: 'Generated script from extraction',
      });
    }
  }

  return snippets;
}

function getToolRequirement(tech: string): string {
  const toolMap: Record<string, string> = {
    'Python': 'Python 3.10+ with venv',
    'JavaScript': 'Node.js 18+ and npm',
    'TypeScript': 'Node.js 18+ and npm',
    'React': 'Node.js 18+ and npm',
    'Next.js': 'Node.js 18+ and npm',
    'Node.js': 'Node.js 18+',
    'FastAPI': 'Python 3.10+ with pip',
    'Django': 'Python 3.10+ with pip',
    'Flask': 'Python 3.10+ with pip',
    'PostgreSQL': 'PostgreSQL 14+',
    'MongoDB': 'MongoDB 6+',
    'Redis': 'Redis 7+',
    'Docker': 'Docker Desktop 4+',
    'Kubernetes': 'kubectl + k8s cluster',
    'AWS': 'AWS CLI configured',
    'Cloudflare': 'Cloudflare account',
  };
  
  return toolMap[tech] || tech;
}

// Re-export for convenience
export { generateManifest, extractKeyConcepts };
