import fs from 'fs';
import path from 'path';
import { tmpdir } from 'os';

interface ParsedCookie {
  name: string;
  value: string;
  domain: string;
  path: string;
  expires: number;
  secure: boolean;
}

function parseCookieString(cookieString: string): ParsedCookie[] {
  const cookies: ParsedCookie[] = [];
  const pairs = cookieString.split(';').map(s => s.trim()).filter(Boolean);

  for (const pair of pairs) {
    const eqIndex = pair.indexOf('=');
    if (eqIndex === -1) continue;

    const name = pair.substring(0, eqIndex).trim();
    const value = pair.substring(eqIndex + 1).trim();

    if (name) {
      cookies.push({
        name,
        value,
        domain: '.instagram.com',
        path: '/',
        expires: 0,
        secure: true,
      });
    }
  }

  return cookies;
}

function cookiesToNetscapeFormat(cookies: ParsedCookie[]): string {
  const lines: string[] = [
    '# Netscape HTTP Cookie File',
    '# This file was generated by Vext-ai',
    '',
  ];

  for (const cookie of cookies) {
    const domain = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expires = cookie.expires || 0;
    const path = cookie.path || '/';

    lines.push(
      `${cookie.domain}\t${domain}\t${path}\t${secure}\t${expires}\t${cookie.name}\t${cookie.value}`
    );
  }

  return lines.join('\n');
}

export interface CookieFileResult {
  filePath: string;
  cleanup: () => void;
}

export function createCookieFile(cookieString: string): CookieFileResult {
  const cookies = parseCookieString(cookieString);

  if (cookies.length === 0) {
    throw new Error('No valid cookies found in cookie string');
  }

  const fileName = `vext-instagram-cookies-${Date.now()}.txt`;
  const filePath = path.join(tmpdir(), fileName);

  const netscapeContent = cookiesToNetscapeFormat(cookies);
  fs.writeFileSync(filePath, netscapeContent, 'utf-8');

  const cleanup = () => {
    try {
      if (fs.existsSync(filePath)) {
        fs.unlinkSync(filePath);
      }
    } catch (error) {
      console.error('[CookieFile] Failed to cleanup cookie file:', error);
    }
  };

  return { filePath, cleanup };
}

export function validateCookieString(cookieString: string): { valid: boolean; sessionId?: string; error?: string } {
  if (!cookieString || cookieString.trim().length === 0) {
    return { valid: false, error: 'Cookie string is empty' };
  }

  const cookies = parseCookieString(cookieString);

  if (cookies.length === 0) {
    return { valid: false, error: 'No valid cookies found' };
  }

  const sessionId = cookies.find(c => c.name === 'sessionid' || c.name === 'session_id');
  const hasSession = !!sessionId;

  if (!hasSession) {
    return { valid: false, error: 'No sessionid cookie found. Please provide valid Instagram session cookies.' };
  }

  return { valid: true, sessionId: sessionId?.value };
}
