import fs from 'fs';
import path from 'path';
import { tmpdir } from 'os';

interface ParsedCookie {
  name: string;
  value: string;
  domain: string;
  path: string;
  expires: number;
  secure: boolean;
}

// Netscape HTTP Cookie File line: domain\tincludeSubdomains\tpath\tsecure\texpiry\tname\tvalue
const NETSCAPE_LINE = /^([^\t]+)\t([^\t]+)\t([^\t]+)\t([^\t]+)\t(\d+)\t([^\t]+)\t(.*)$/;

function isNetscapeLine(line: string): boolean {
  return NETSCAPE_LINE.test(line);
}

function parseNetscapeCookies(content: string): ParsedCookie[] {
  const cookies: ParsedCookie[] = [];
  const instagramDomains = ['instagram.com', '.instagram.com', 'www.instagram.com'];

  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;

    const match = line.match(NETSCAPE_LINE);
    if (!match) continue;

    const domain = match[1];
    if (!instagramDomains.includes(domain) && !domain.endsWith('.instagram.com')) continue;

    const path = match[3];
    const secure = match[4] === 'TRUE';
    const expires = parseInt(match[5], 10) || 0;
    const name = match[6];
    const value = match[7];

    if (!name) continue;

    cookies.push({
      name,
      value,
      domain,
      path,
      expires,
      secure,
    });
  }

  return cookies;
}

function parseCookieString(cookieString: string): ParsedCookie[] {
  const trimmed = cookieString.trim();
  if (!trimmed) return [];

  // Detect full Netscape HTTP Cookie File dump (tab-separated lines)
  if (trimmed.includes('\n') && trimmed.split(/\r?\n/).some(isNetscapeLine)) {
    return parseNetscapeCookies(trimmed);
  }

  const cookies: ParsedCookie[] = [];
  const pairs = trimmed.split(';').map(s => s.trim()).filter(Boolean);

  for (const pair of pairs) {
    const eqIndex = pair.indexOf('=');
    if (eqIndex === -1) continue;

    const name = pair.substring(0, eqIndex).trim();
    const value = pair.substring(eqIndex + 1).trim();

    if (name) {
      cookies.push({
        name,
        value,
        domain: '.instagram.com',
        path: '/',
        expires: 0,
        secure: true,
      });
    }
  }

  return cookies;
}

function cookiesToNetscapeFormat(cookies: ParsedCookie[]): string {
  const lines: string[] = [
    '# Netscape HTTP Cookie File',
    '# This file was generated by Vext-ai',
    '',
  ];

  for (const cookie of cookies) {
    const domain = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expires = cookie.expires || 0;
    const path = cookie.path || '/';

    lines.push(
      `${cookie.domain}\t${domain}\t${path}\t${secure}\t${expires}\t${cookie.name}\t${cookie.value}`
    );
  }

  return lines.join('\n');
}

export interface CookieFileResult {
  filePath: string;
  cleanup: () => void;
}

export function createCookieFile(cookieString: string): CookieFileResult {
  const cookies = parseCookieString(cookieString);

  if (cookies.length === 0) {
    throw new Error('No valid cookies found in cookie string');
  }

  const fileName = `vext-instagram-cookies-${Date.now()}.txt`;
  const filePath = path.join(tmpdir(), fileName);

  const netscapeContent = cookiesToNetscapeFormat(cookies);
  fs.writeFileSync(filePath, netscapeContent, 'utf-8');

  const cleanup = () => {
    try {
      if (fs.existsSync(filePath)) {
        fs.unlinkSync(filePath);
      }
    } catch (error) {
      console.error('[CookieFile] Failed to cleanup cookie file:', error);
    }
  };

  return { filePath, cleanup };
}

export function validateCookieString(cookieString: string): { valid: boolean; sessionId?: string; error?: string } {
  if (!cookieString || cookieString.trim().length === 0) {
    return { valid: false, error: 'Cookie string is empty' };
  }

  const cookies = parseCookieString(cookieString);

  if (cookies.length === 0) {
    return { valid: false, error: 'No valid cookies found' };
  }

  const sessionId = cookies.find(c => c.name === 'sessionid' || c.name === 'session_id');
  const hasSession = !!sessionId;

  if (!hasSession) {
    return { valid: false, error: 'No sessionid cookie found. Please provide valid Instagram session cookies.' };
  }

  return { valid: true, sessionId: sessionId?.value };
}
