'use client';

import { Button } from './Button';
import { Download, Loader2 } from 'lucide-react';
import { useState } from 'react';
import JSZip from 'jszip';

interface AgentZipButtonProps {
  output: any;
  shareId: string;
}

export function AgentZipButton({ output, shareId }: AgentZipButtonProps) {
  const [isZipping, setIsZipping] = useState(false);

  const generateReadme = (output: any) => {
    return `# God Mode Blueprint: ${output.title || 'SaaS Intelligence'}

## 💡 Core Opportunity
**Problem:** ${output.core_opportunity?.problem_statement || 'N/A'}
**Market Size:** ${output.core_opportunity?.target_market || 'N/A'}
**Gap in Market:** ${output.core_opportunity?.gap_in_market || 'N/A'}
**Existing Solutions:** ${(output.core_opportunity?.existing_solutions || []).join(', ')}

## 🛠 Technical Architecture
**Recommended Stack:** ${(output.technical_blueprint?.recommended_stack || []).join(', ')}
**External APIs:** ${(output.technical_blueprint?.external_apis || []).join(', ')}

### Data Model
**Tables:** ${(output.technical_blueprint?.data_model?.tables_or_collections || []).join(', ')}
**Relationships:** ${output.technical_blueprint?.data_model?.key_relationships || 'N/A'}

## 💰 Business Model
**Revenue Streams:** ${(output.business_model?.revenue_streams || []).join(', ')}
**Pricing:** ${(output.business_model?.pricing_models || []).join(', ')}
**CAC:** $${output.business_model?.unit_economics?.cac_estimate}
**LTV:** $${output.business_model?.unit_economics?.ltv_estimate}
**Payback:** ${output.business_model?.unit_economics?.payback_period}

## 🛡 The Moat
**Switching Costs:** ${output.moat_analysis?.switching_costs}
**Brand Advantage:** ${output.moat_analysis?.brand_advantage}
**Network Effects:** ${output.moat_analysis?.network_effects ? 'Yes' : 'No'}
**Data Network Effects:** ${output.moat_analysis?.data_network_effects ? 'Yes' : 'No'}

## 🚀 Execution Roadmap
**Month 1 (MVP):**
${(output.execution_roadmap?.month_1_mvp || []).map((t: string) => `- ${t}`).join('\n')}

**Month 2 (Traction):**
${(output.execution_roadmap?.month_2_traction || []).map((t: string) => `- ${t}`).join('\n')}

**Month 3 (Scale):**
${(output.execution_roadmap?.month_3_scale || []).map((t: string) => `- ${t}`).join('\n')}

---
*Generated by Vext God Mode Engine*
`;
  };

  const handleDownloadZip = async () => {
    setIsZipping(true);
    try {
      const zip = new JSZip();

      // 1. Raw JSON
      zip.file("blueprint.json", JSON.stringify(output, null, 2));

      // 2. README.md
      zip.file("README.md", generateReadme(output));

      // 3. Prompts
      const promptsFolder = zip.folder("prompts");
      output.technical_blueprint?.prompts_to_generate?.forEach((p: any, index: number) => {
        promptsFolder?.file(`system_prompt_${index + 1}.txt`, p.system_prompt_text || "");
        promptsFolder?.file(`user_template_${index + 1}.txt`, p.user_prompt_template || "");
      });

      // 4. Generated Scripts
      const scriptsFolder = zip.folder("scripts");
      scriptsFolder?.file("starter_logic.js", output.technical_blueprint?.starter_code_snippet || "");
      output.generated_files?.scripts?.forEach((f: any) => {
        if (f.filename) {
          scriptsFolder?.file(f.filename, f.content || "");
        }
      });

      // 5. Generated Configs
      const configsFolder = zip.folder("configs");
      output.generated_files?.configs?.forEach((f: any) => {
        if (f.filename) {
          configsFolder?.file(f.filename, f.content || "");
        }
      });

      // Generate the zip blob
      const content = await zip.generateAsync({ type: "blob" });

      // Trigger download
      const url = URL.createObjectURL(content);
      const link = document.createElement("a");
      link.href = url;
      link.download = `Vext_Agent_Archive_${shareId}.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Failed to generate zip", error);
    } finally {
      setIsZipping(false);
    }
  };

  return (
    <Button 
      variant="primary" 
      onClick={handleDownloadZip}
      disabled={isZipping}
      className="gap-2 shadow-[0_0_15px_rgba(0,255,255,0.3)] animate-pulse hover:animate-none"
    >
      {isZipping ? (
        <Loader2 className="w-4 h-4 animate-spin" />
      ) : (
        <Download className="w-4 h-4" />
      )}
      Export for SWE Agent
    </Button>
  );
}
